Update Dockerfile
openchatai/OpenChat pull request #147
Opened 2023-08-22 10:08 UTC by mrtrantuan

Fixed:
ERROR: Service 'llm-server' failed to build: COPY failed: stat my-space/package-lock.json: file does not exist

2023-08-22 11:13 UTC, shanurrahmanpenny approved these changes

2023-08-22 11:16 UTC, shanurrahmanpenny requested changes

2023-08-22 11:16 UTC, shanurrahmanpenny commented on llm-server/Dockerfile
> +# COPY --from=builder /my-space/package-lock.json .
Hello @mrtrantuan , considering that we're utilizing 'yarn install', it's important to have a yarn.lock file present. Could you please verify that this line is adjusted to include the copying of the yarn.lock file? Your outstanding efforts are highly valued. Thank you very much.

2023-08-22 11:57 UTC, merged

2023-08-22 11:58 UTC, codebanesr commented
@mrtrantuan I realised my mistake. You're right, we don't need the lockfile in second stage of build because we are not going to ru `npm install`. Thanks again

2024-11-01 19:52 UTC, LegacyCEODigital commented
Hello